version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: patentscout_postgres
    restart: always
    environment:
      POSTGRES_USER: patentscout
      POSTGRES_PASSWORD: patentscout_pass
      POSTGRES_DB: patentscout_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
